main: op.lessnop.Main
version: 1.2.1
name: Otchlan
commands:
  otchlan:
    description: Otworz otchlan.
    aliases: [ot]
  otchlanadmin:
    description: Zarzadzanie pluginem.
    aliases: [otadmin]
